Feature
masouma2020/Portfolio pull request #1
Opened 2022-08-18 21:04 UTC by masouma2020

I made some change in readme file

2022-08-19 07:53 UTC, frank1738 requested changes
Hi  @masouma2020 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![woohoo-youre-almost](https://user-images.githubusercontent.com/77038610/154921145-1f7bb8f6-c843-4ba5-a534-6b840c600558.jpeg)

## Highlights
- Have used the right GitHub flow ✅
- Linter checks passed ✅




## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 07:53 UTC, frank1738 commented on index.html
> +              <img src="images/hamberger.png" class="button" alt="hamberger" />
- [ ] would you please wrap your hamburger button inside a `<nav>` tag. This is important for semantic and accessibility purposes

2022-08-19 07:53 UTC, frank1738 commented on index.html
> +    <div class="container">
- [ ] Would you please create a `<header>` section that is supposed to contain your logo and hamburger button  `that is the toolbar`  and another `<section>` that is supposed to contain your headline. This is important for semantic and accessibility reasons

2022-08-19 07:53 UTC, frank1738 commented on index.html
> +          </div>
- [ ] Would you please use `<ul>` to group your skills and `<li>` for each skills. This is important for semantic and accessibility reasons

2022-08-19 07:53 UTC, frank1738 commented on style.css
> +}
- [ ] You have done a good job trying to implement the Figma design but there are some aspects I need you to consider  
   - On your toolbar, would you please use the hamburger button 
       used on the Figma design and try to align your items 
       properly. ` hint `  Use align-items: center

![image](https://user-images.githubusercontent.com/98453979/185569581-cf920d42-22ae-4725-9e51-058dbca99706.png)

   - On your headline, would you please 
        consider the spacing of your elements, use the font used on 
         the Figma design  and try to align them 
         to the center
 
![image](https://user-images.githubusercontent.com/98453979/185570096-5d17b41a-c6d4-43f5-a253-4121802de31e.png)

2022-08-19 08:35 UTC, merged

2022-08-19 08:38 UTC, masouma2020 commented
thanks for all your effort

2022-08-19 08:57 UTC, mahbubul14 reviewed
Hi @masouma2020 ,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] Kindly check all the suggestions by the previous reviewer and fix the issue he mentioned. If you don't understand anything you can ask for help also. arrow_down: 

**Note:** Please don't merge your branch before getting approved.

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Github flow used properly.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

- [ ] The commit message should be written in the imperative tense. `Ex: "Fix bug" instead of "Fixed bug"/ "bug fixing" etc.` [For more details.](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-08-19 16:24 UTC, tugsem commented
Hi @masouma2020 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔴 🔴 

The student didn't implement requested changes by the prior reviewers.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-19 16:27 UTC, bobb-Rob reviewed
### Hi @masouma2020 , 

Great work on creating this project to this point 👏 
You've done well so far but you can do more by implementing the requested changes by the previous reviewer [here](https://github.com/masouma2020/Portfolio/pull/1/files#r949890298).

You absolutely got this 🔋 🔥 🔥 💪 

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Neat Commit messages


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 16:27 UTC, bobb-Rob commented on index.html
> +          </div>
### I noticed you did not implement all the issues raised by the first reviewer @frank1738. Kindly implement the issues he raised so that you can move ahead.  Just to mention, you should never merge a pull request that has not been approved, you only merge a pull request after a reviewer has approved it. please take note of this for future projects. 

- [ ] [OPTIONAL] You do not need to implement this section in this project as this comes with the mobile. Please remove this section - `<div id="group">` and its children as it is completely unnecessary for this project. 
![image](https://user-images.githubusercontent.com/84156714/185662191-f53c09d7-ed90-4c58-98e1-c7ec04037df7.png)

2022-08-19 22:56 UTC, masouma2020 commented on index.html
> +    <div class="container">
I code reviewer
I made all changes, let me submit  it

2022-08-19 22:57 UTC, masouma2020 commented
check my project

2022-08-20 00:11 UTC, ElsonOtake reviewed
Hi @masouma2020, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Invalid code review request](https://media.makeameme.org/created/invalid-code-review-5f2c677fb9.jpg)

## Invalid Code Review Request

You have submitted a project, that did not implement changes requested by other reviewers and the merge made it difficult to review the remaining code. You can request a second opinion on this [link](https://airtable.com/shrQAqnBwek5a0O0s).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏 🙏 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._